-- ==========================================================
-- SuperAdmin Migration Script
-- Run this against BankuPG database ONCE to create the tables
-- ==========================================================

-- 1. SuperAdmins table
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'SuperAdmins')
BEGIN
    CREATE TABLE SuperAdmins (
        AdminID          INT            IDENTITY(1,1)  NOT NULL,
        Username         NVARCHAR(100)  NOT NULL,
        Email            NVARCHAR(255)  NOT NULL,
        PasswordHash     NVARCHAR(512)  NOT NULL,
        Salt             NVARCHAR(256)  NOT NULL,
        Role             NVARCHAR(50)   NOT NULL  CONSTRAINT DF_SuperAdmins_Role     DEFAULT ('SuperAdmin'),
        IsActive         BIT            NOT NULL  CONSTRAINT DF_SuperAdmins_IsActive  DEFAULT (1),
        IsLocked         BIT            NOT NULL  CONSTRAINT DF_SuperAdmins_IsLocked  DEFAULT (0),
        FailedLoginAttempts INT         NOT NULL  CONSTRAINT DF_SuperAdmins_FailedLoginAttempts DEFAULT (0),
        LastLoginDate    DATETIME       NULL,
        CreatedDate      DATETIME       NOT NULL  CONSTRAINT DF_SuperAdmins_CreatedDate  DEFAULT (GETDATE()),
        UpdatedDate      DATETIME       NULL       CONSTRAINT DF_SuperAdmins_UpdatedDate  DEFAULT (GETDATE()),

        CONSTRAINT PK__SuperAdm__719FE48802A36FBE PRIMARY KEY CLUSTERED (AdminID),
        CONSTRAINT UQ__SuperAdm__Username UNIQUE (Username),
        CONSTRAINT UQ__SuperAdm__Email    UNIQUE (Email)
    );

    PRINT 'Table SuperAdmins created.';
END
ELSE
BEGIN
    PRINT 'Table SuperAdmins already exists – skipped.';
END
GO

-- 2. SuperAdminRefreshTokens table
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'SuperAdminRefreshTokens')
BEGIN
    CREATE TABLE SuperAdminRefreshTokens (
        RefreshTokenID  INT            IDENTITY(1,1)  NOT NULL,
        AdminID         INT            NOT NULL,
        Token           NVARCHAR(500)  NOT NULL,
        ExpiresAt       DATETIME       NOT NULL,
        CreatedAt       DATETIME       NOT NULL  CONSTRAINT DF_SuperAdmRT_CreatedAt DEFAULT (GETDATE()),
        IsRevoked       BIT            NOT NULL  CONSTRAINT DF_SuperAdmRT_IsRevoked DEFAULT (0),
        RevokedAt       DATETIME       NULL,
        IpAddress       NVARCHAR(50)   NULL,
        UserAgent       NVARCHAR(500)  NULL,

        CONSTRAINT PK__SuperAdm__RefreshToken       PRIMARY KEY CLUSTERED (RefreshTokenID),
        CONSTRAINT UQ__SuperAdmRefreshT__Token       UNIQUE (Token),
        CONSTRAINT FK_SuperAdminRefreshTokens_SuperAdmins
            FOREIGN KEY (AdminID) REFERENCES SuperAdmins (AdminID) ON DELETE CASCADE
    );

    CREATE INDEX IX__SuperAdmRefreshT__AdminId
        ON SuperAdminRefreshTokens (AdminID);

    PRINT 'Table SuperAdminRefreshTokens created.';
END
ELSE
BEGIN
    PRINT 'Table SuperAdminRefreshTokens already exists – skipped.';
END
GO

-- ==========================================================
-- 3. Seed a default SuperAdmin account
--
--    Username : superadmin
--    Password : Admin@1234
--
--    PasswordHash / Salt generated via the app's PasswordService
--    (PBKDF2-SHA256, 10 000 iterations, 16-byte salt, 32-byte hash)
--
--    REPLACE the values below with hashes generated by running the
--    app's PasswordService.HashPassword("Admin@1234") and copying
--    the resulting hash + salt here before executing.
-- ==========================================================
IF NOT EXISTS (SELECT 1 FROM SuperAdmins WHERE Username = 'superadmin')
BEGIN
    INSERT INTO SuperAdmins (Username, Email, PasswordHash, Salt, Role, IsActive, IsLocked, FailedLoginAttempts)
    VALUES (
        'superadmin',
        'admin@banku.in',
        'REPLACE_WITH_PBKDF2_HASH',   -- PasswordService.HashPassword result
        'REPLACE_WITH_SALT',          -- corresponding Salt
        'SuperAdmin',
        1,
        0,
        0
    );

    PRINT 'Default SuperAdmin seed inserted.';
END
GO
